version: '2'
services:
  web:
    image: lloydkirk/kalesville:0.0.11
    build:
      context: ../../
      dockerfile: ./devops/kalesville/Dockerfile
    container_name: kalesville-web
    external_links:
      - kalesville-pg:kalesville-pg
    depends_on:
      - kalesville-pg

  web-dev:
    image: lloydkirk/kalesville:dev
    build:
      context: ../../
      dockerfile: ./devops/kalesville/Dockerfile-dev
    container_name: kalesville-web-dev
    external_links:
      - kalesville-pg-dev:kalesville-pg
    depends_on:
      - kalesville-pg-dev
    volumes:
      - ../../app:/opt/kalesville/app:ro
      - ../../static/js/public:/opt/kalesville/static/js/public/:rw
      - ../../static/js/app:/opt/kalesville/static/js/app:ro
