version: '2'
services:
  # web:
  #   build:
  #     context: ../../
  #     dockerfile: ./devops/kalesville/Dockerfile
  #   container_name: kalesville-web
  #   environment:
  #     - APP_ENV=docker
  #   external_links:
  #     - kalesville-mysql:mysql
  #   depends_on:
  #     - nginx

  web-dev:
    image: lloydkirk/kalesville:dev
    build:
      context: ../../
      dockerfile: ./devops/kalesville/Dockerfile-dev
    container_name: kalesville-web-dev
    external_links:
      - kalesville-pg
      - nginx:nginx
    depends_on:
      - kalesville-pg
      - nginx-dev
