FROM node:7.5.0
RUN set -e; \
    # setup user and space for code
    useradd -ms /bin/bash user; \
    mkdir /opt/kalesville; \ 
    chown user:user /opt/kalesville

WORKDIR /opt/kalesville
ADD . .
RUN chown -R user:user /opt/kalesville
USER user
RUN npm install
CMD ["npm", "run", "dev"]
