version: '2'
services:
  web:
    build:
      context: ../../
      dockerfile: ./devops/kalesville/Dockerfile
    environment:
      - APP_ENV=docker
    external_links:
      - kalesville-mysql:mysql
    ports:
      - "5000:5000"
    external_links:
      - kalesville-mysql:mysql
    depends_on:
      - kalesville-mysql

  web-dev:
    build:
      context: ../../
      dockerfile: ./devops/kalesville/Dockerfile-dev
      image: lloydkirk/kalesville:dev
    environment:
      - APP_ENV=docker
    external_links:
      - kalesville-mysql-dev:mysql
    ports:
      - "5000:5000"
    depends_on:
      - kalesville-mysql-dev
    volumes:
      - ../../app.lisp:/opt/kalesville/app.lisp:ro
      - ../../.babelrc:/opt/kalesville/.babelrc:ro
      - ../../devops:/opt/kalesville/devops:ro
      - ../../kalesville.asd:/opt/kalesville/kalesville.asd:ro
      - ../../kalesville-test.asd:/opt/kalesville/kalesville-test.asd:ro
      - ../../Makefile:/opt/kalesville/Makefile:ro
      - ../../package.json:/opt/kalesville/package.json:ro
      - ../../scripts:/opt/kalesville/scripts:ro
      - ../../src:/opt/kalesville/src:ro
      - ../../static/js/app:/opt/kalesville/static/js/app:ro
      - ../../static/css:/opt/kalesville/static/css:ro
      - ../../t:/opt/kalesville/t:ro
      - ../../templates:/opt/kalesville/templates:ro
      - ../../webpack.config.js:/opt/kalesville/webpack.config.js:ro
