FROM debian:8.6
RUN set -e; \

    # setup user and space for code
    useradd -ms /bin/bash user; \
    mkdir /opt/kalesville; \ 
    chown user:user /opt/kalesville; \

    apt-get update; \
    apt-get install -y \

    	    # required for operation
	    ca-certificates \
	    make \
	    bzip2 \
	    libmysqlclient-dev \

	    # needed for roswell build
    	    autoconf \
	    gcc \
	    git \
	    libcurl4-gnutls-dev \
	    curl \

	    # needed for npm build
	    python \
	    g++ \
	    ; \

    # build roswell
    cd /opt \
    && git clone -b release https://github.com/roswell/roswell.git \
    && cd roswell \
    && sh bootstrap && ./configure && make && make install

    # build npm
RUN cd /opt \
    && git clone -b v7.1.0 https://github.com/nodejs/node \
    && cd node \
    && ./configure && make install

    # clean after build
RUN apt-get remove -y --purge \
    	    autoconf \
    	    gcc \
    	    git \
    	    libcurl4-gnutls-dev \
    	    curl \
	    python \
	    g++ \
	    ;\

    rm -r /opt/roswell /opt/node

WORKDIR /opt/kalesville
# add in kalesville source code
ADD . .
RUN chown -R user:user .

USER user

# boostrap roswell clack quicklisp and kalesville libraries
RUN ros setup; \
    ln -s /opt/kalesville/ ~/.roswell/local-projects/kalesville; \
    ros install clack; \
    ./scripts/pkg-init.ros;

# bootstrap kalesville node build
RUN npm install

# CMD ["/home/user/.roswell/bin/clackup","--server",":hunchentoot","--port","5000","app.lisp"]
CMD ["./scripts/run-web-dev"]
