sudo: required
language: go

branches:
  except:
    - master

go:
  - 1.8.1

services:
  - docker

env:
  - TRAVIS_NODE_VERSION=7.5.0

install: ./scripts/travis/install

script: ./scripts/travis/build

after_success: ./scripts/travis/push-docker
