sudo: required
language: go

go:
  - 1.8.1

services:
  - docker

env:
  - TRAVIS_NODE_VERSION=7.9.0

install: ./scripts/travis/install

script: ./scripts/travis/build

after_success: ./scripts/travis/push-docker
