sudo: required
language: go

go:
  - 1.8.1

services:
  - docker

install:
  - go get github.com/Masterminds/glide
  - go get github.com/jteeuwen/go-bindata

before_script:
  - git describe > VERSION

script: |
  if [ "$TRAVIS_BRANCH" = master ]; then
    make build-web
  else
    make build-web-dev
  fi

after_success: |
  docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  if [ "$TRAVIS_BRANCH" = master ]; then
    echo 'will push to prd when ready'
  else
    docker push 'lloydkirk/kalesville:dev'
  fi
