sudo: required
language: go

go:
  - 1.8.1

services:
  - docker

env:
  - TRAVIS_NODE_VERSION="7.9.0"

install:
  - go get github.com/Masterminds/glide
  - go get github.com/jteeuwen/go-bindata
  - >-
    rm -rf ~/.nvm
    && git clone https://github.com/creationix/nvm.git ~/.nvm
    && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`)
    && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION

before_script:
  - git describe > VERSION
  - scripts/increment-version patch < VERSION > NEXT_VERSION
  - touch ~/.kalesville-env-prd # TODO: hack for now

script: |
  if [ "$TRAVIS_BRANCH" = master ]; then
    make build-web
  else
    make build-web-dev
  fi

after_success: |
  docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  if [ "$TRAVIS_BRANCH" = master ]; then
    echo 'will push to prd when ready'
  else
    docker push 'lloydkirk/kalesville:dev'
  fi
