sudo: required

services:
  - docker

script: |
  if [ "$TRAVIS_BRANCH" = master ]; then
    make build-web
  elif [ "$TRAVIS_BRANCH" = dev ]; then
    make build-web-dev
  else
    echo 'unable to parse branch' >&2 && exit 1
  fi

after_success: |
  docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
  if [ "$TRAVIS_BRANCH" = master ]; then
    echo 'will push to prd when ready'
  elif [ "$TRAVIS_BRANCH" = dev ]; then
    docker push 'lloydkirk/kalesville:dev'
  else
    echo 'unable to parse branch' >&2 && exit 1
  fi
