---
- hosts: kalesville-dev
  vars:
    ansible_python_interpreter: /home/core/python
  gather_facts: no
  tasks:

    - name: UP:kalesville-(PRD) 
      docker_service:
        project_name: kalesville
        project_src: /home/core/kalesville/prd
        pull: yes
        build: no
        state: present
      tags: up

    - name: DOWN:kalesville-(PRD)
      docker_service:
        project_name: kalesville
        pull: yes
        build: no
        state: absent
        project_src: /home/core/kalesville/prd
      tags: down
