- name: Run with inline v2 compose
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - docker_service:
        project_name: kalesville
        definition:
          version: '2'
          services:
            web:
              image: lloydkirk/kalesville:0.0.8
              build:
                context: ../../
                dockerfile: ./devops/kalesville/Dockerfile
              container_name: kalesville-web
              external_links:
                - kalesville-pg:kalesville-pg
              depends_on:
                - kalesville-pg

            nginx:
              build:
                context: ../../
                dockerfile: ./devops/nginx/Dockerfile
              image: lloydkirk/kalesville-nginx:0.0.8
              container_name: nginx
              ports:
                - "80:80"
                - "443:443"
              external_links:
                - web:kalesville
              depends_on:
                - web

            kalesville-pg:
              image: postgres:9.6
              container_name: kalesville-pg
              hostname: kalesville-pg
              ports:
                - "5432:5432"
              volumes:
                - /opt/kalesville/pg-prd:/var/lib/postgresql/data:rw
              env_file:
                - /home/lkirk/.kalesville-env-prd
              environment:
                - POSTGRES_DB=kalesville-web
      # register: output
      # become: true

    - debug:
        var: output

    # - assert:
    #     that:
    #       - "web.flask_web_1.state.running"
    #       - "db.flask_db_1.state.running"
