#!/bin/bash

set -exo pipefail

git fetch -t
git describe > VERSION
touch ~/.kalesville-env-prd

if $(egrep -q '[0-9]+\.[0-9]+\.[0-9]+' <<< "$TRAVIS_BRANCH"); then
    set +x
    source ~/.nvm/nvm.sh
    set -x
    npm install
    npm build
    glide install
    CGO_ENABLED=0 go build
    make build-web build-nginx
else
    make build-web-dev build-nginx-dev
fi
