#!/bin/sh

set -ex

go get github.com/Masterminds/glide
go get github.com/jteeuwen/go-bindata

if [ "$TRAVIS_BRANCH" = master ]; then
    rm -rf ~/.nvm
    git clone https://github.com/creationix/nvm.git ~/.nvm
    (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`)
    source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
fi
