#!/bin/bash

set -exo pipefail

go get github.com/Masterminds/glide
go get github.com/jteeuwen/go-bindata

# if $(egrep -q '[0-9]+\.[0-9]+\.[0-9]+' <<< "$TRAVIS_BRANCH"); then
set +x
rm -rf ~/.nvm
git clone https://github.com/creationix/nvm.git ~/.nvm
(cd ~/.nvm && git checkout $(git describe --abbrev=0 --tags))
source ~/.nvm/nvm.sh
nvm install $TRAVIS_NODE_VERSION
(npm install)
# fi
