#!/bin/bash

set -eo pipefail
docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

[[ ! -e VERSION ]] && echo 'VERSION file not found' >&2 && exit 1

VERSION=$(< VERSION)
echo "==== Version: $VERSION ===="

if $(egrep -q '[0-9]+\.[0-9]+\.[0-9]+' <<< "$TRAVIS_BRANCH"); then
    set -x
    docker push "lloydkirk/kalesville:$VERSION"
    docker push "lloydkirk/kalesville-nginx:$VERSION"
else
    set -x
    docker push 'lloydkirk/kalesville:dev'
fi
